---
- name: install ssmtp
  become: yes
  apt:
    name={{ item }}
    state=present
    update_cache=yes
    cache_valid_time=3600
  with_items:
    - ssmtp
    - mailutils

- name: create group for mail sending
  become: yes
  group:
    name="mail-user"
    state=present

- name: add ansible user to allowed mail senders
  become: yes
  user:
    name=ansible
    append=yes
    groups="mail-user"
    state=present

- name: install ssmtp configuration
  become: yes
  template:
    src=ssmtp.conf.j2
    dest=/etc/ssmtp/ssmtp.conf
    owner=root
    group="mail-user"
    mode=0640
